name: CI/CD Static Web App

on:
  push:
    branches: ["main"]


jobs:
  ci:
    name: Validate HTML and JS
    runs-on: ubuntu-latest
    steps:

     # Ce bloc sert à récupérer le code de votre dépôt dans la machine GitHub Actions (le runner), pour que les étapes suivantes puissent lire vos fichiers.

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check JavaScript syntax
        run: node --check app.js